### ISSUE TITLE
CI failing on main: mobile typecheck errors and web lint duplicate-import errors

### ISSUE THREAD

**Issue by saliou673** [saliou673/spring-next-saas-starter#151]
Both CI jobs are red on the current tip of `main` (confirmed on commit `360a646`, i.e. pre-existing — not caused by #147/#149's merges in #148/#150). Run: https://github.com/saliou673/spring-next-saas-starter/actions/runs/31995043739

## Mobile (lint, typecheck, build) — typecheck failure

```
src/components/animated-icon.web.tsx(5,21): error TS2307: Cannot find module './animated-icon.module.css' or its corresponding type declarations.
src/constants/theme.ts(6,8): error TS2882: Cannot find module or type declarations for side-effect import of '@/global.css'.
```

(Note: `animated-icon.web.tsx`'s import of `./animated-icon.module.css` no longer exists as of #150 — that specific line is gone — but the underlying cause, missing CSS-module/global-CSS type declarations in the typecheck environment, is still live via `src/constants/theme.ts`'s `@/global.css` import and would resurface for any other `.module.css` import. Needs investigation into why CSS type declarations aren't being generated/found in CI.)

## Web (lint, build) — ESLint failure

`no-duplicate-imports` errors (7 errors) in files that import `@api-client` twice:
- `app/sign-up/sign-up-form.tsx` (lines 12, 17)
- `src/features/configurations/configurations-delete-dialog.tsx` (line 6)
- `src/features/configurations/configurations-form-dialog.tsx` (line 40)
- `src/features/users/components/users-action-dialog.tsx` (line 19)
- `src/features/users/components/users-delete-dialog.tsx` (line 14)
- `src/features/users/components/users-multi-delete-dialog.tsx` (line 15)

Plus 5 `Unused eslint-disable directive` warnings (non-blocking) in `direction-provider.tsx`, `font-provider.tsx`, `layout-provider.tsx`, `search-provider.tsx`, `theme-provider.tsx`.

## Scope
- Fix the mobile typecheck CSS-module/global-CSS type-declaration issue
- Merge the duplicate `@api-client` imports in the six web files listed above
- Get `main`'s CI pipeline green again
